// 等級設定（標籤顯示用）
const LEVEL_CONFIG = {
  starters: { label: 'Starters', color: '🌱' },
  movers:   { label: 'Movers',   color: '🚶‍♂️' },
  flyers:   { label: 'Flyers',   color: '🕊️' }
};

// ★ 下面這三個物件，請依照你的單字資料填 ★

    const STARTERS_DATA = {
      categories: [
    {
      "id": "family",
      "label": "家人 & 人物",
      "icon": "👨‍👩‍👧‍👦",
      "words": [
        { "en": "father",  "pos": "n", "zh": "爸爸" },
        { "en": "mother",  "pos": "n", "zh": "媽媽" },
        { "en": "dad",     "pos": "n", "zh": "爸爸（口語）" },
        { "en": "mum",     "pos": "n", "zh": "媽媽（口語）" },
        { "en": "brother", "pos": "n", "zh": "兄弟" },
        { "en": "sister",  "pos": "n", "zh": "姐妹" },
        { "en": "grandma", "pos": "n", "zh": "奶奶；外婆" },
        { "en": "grandpa", "pos": "n", "zh": "爺爺；外公" },
        { "en": "grandmother", "pos": "n", "zh": "祖母" },
        { "en": "grandfather", "pos": "n", "zh": "祖父" },
        { "en": "family",  "pos": "n", "zh": "家庭；家人" },
        { "en": "friend",  "pos": "n", "zh": "朋友" },
        { "en": "baby",    "pos": "n", "zh": "嬰兒" },
        { "en": "man",     "pos": "n", "zh": "男人" },
        { "en": "men",     "pos": "n", "zh": "男人（複數）" },
        { "en": "woman",   "pos": "n", "zh": "女人" },
        { "en": "women",   "pos": "n", "zh": "女人（複數）" },
        { "en": "Miss",    "pos": "title", "zh": "小姐（稱謂）" },
        { "en": "Mr",      "pos": "title", "zh": "先生（稱謂）" },
        { "en": "Mrs",     "pos": "title", "zh": "太太（稱謂）" },
        { "en": "Alex",    "pos": "n", "zh": "亞歷克斯（人名）" },
        { "en": "Alice",   "pos": "n", "zh": "愛麗絲（人名）" },
        { "en": "Ann",     "pos": "n", "zh": "安（人名）" },
        { "en": "Anna",    "pos": "n", "zh": "安娜（人名）" },
        { "en": "Ben",     "pos": "n", "zh": "班（人名）" },
        { "en": "Bill",    "pos": "n", "zh": "比爾（人名）" },
        { "en": "Dan",     "pos": "n", "zh": "丹（人名）" },
        { "en": "Eva",     "pos": "n", "zh": "伊娃（人名）" },
        { "en": "Grace",   "pos": "n", "zh": "葛蕾絲（人名）" },
        { "en": "Hugo",    "pos": "n", "zh": "雨果（人名）" },
        { "en": "Jill",    "pos": "n", "zh": "吉兒（人名）" },
        { "en": "Kim",     "pos": "n", "zh": "金（人名）" },
        { "en": "Lucy",    "pos": "n", "zh": "露西（人名）" },
        { "en": "Mark",    "pos": "n", "zh": "馬克（人名）" },
        { "en": "Matt",    "pos": "n", "zh": "麥特（人名）" },
        { "en": "May",     "pos": "n", "zh": "梅（人名）" },
        { "en": "Nick",    "pos": "n", "zh": "尼克（人名）" },
        { "en": "Pat",     "pos": "n", "zh": "派特（人名）" },
        { "en": "Sam",     "pos": "n", "zh": "山姆（人名）" },
        { "en": "Sue",     "pos": "n", "zh": "蘇（人名）" },
        { "en": "Tom",     "pos": "n", "zh": "湯姆（人名）" }
      ]
    },
    {
      "id": "body",
      "label": "身體",
      "icon": "🧍",
      "words": [
        { "en": "head",   "pos": "n", "zh": "頭" },
        { "en": "hair",   "pos": "n", "zh": "頭髮" },
        { "en": "face",   "pos": "n", "zh": "臉" },
        { "en": "eye",    "pos": "n", "zh": "眼睛" },
        { "en": "ear",    "pos": "n", "zh": "耳朵" },
        { "en": "nose",   "pos": "n", "zh": "鼻子" },
        { "en": "mouth",  "pos": "n", "zh": "嘴巴" },
        { "en": "hand",   "pos": "n", "zh": "手" },
        { "en": "arm",    "pos": "n", "zh": "手臂" },
        { "en": "leg",    "pos": "n", "zh": "腿；腳" },
        { "en": "foot",   "pos": "n", "zh": "腳（單數）" },
        { "en": "feet",   "pos": "n", "zh": "腳（複數）" },
        { "en": "body",   "pos": "n", "zh": "身體" },
        { "en": "tail",   "pos": "n", "zh": "尾巴" }
      ]
    },
    {
      "id": "animals",
      "label": "動物",
      "icon": "🐾",
      "words": [
        { "en": "dog",      "pos": "n", "zh": "狗" },
        { "en": "cat",      "pos": "n", "zh": "貓" },
        { "en": "bird",     "pos": "n", "zh": "鳥" },
        { "en": "fish",     "pos": "n", "zh": "魚" },
        { "en": "frog",     "pos": "n", "zh": "青蛙" },
        { "en": "cow",      "pos": "n", "zh": "牛" },
        { "en": "goat",     "pos": "n", "zh": "山羊" },
        { "en": "sheep",    "pos": "n", "zh": "綿羊" },
        { "en": "horse",    "pos": "n", "zh": "馬" },
        { "en": "duck",     "pos": "n", "zh": "鴨子" },
        { "en": "monkey",   "pos": "n", "zh": "猴子" },
        { "en": "elephant", "pos": "n", "zh": "大象" },
        { "en": "hippo",    "pos": "n", "zh": "河馬" },
        { "en": "giraffe",  "pos": "n", "zh": "長頸鹿" },
        { "en": "lizard",   "pos": "n", "zh": "蜥蜴" },
        { "en": "crocodile","pos": "n", "zh": "鱷魚" },
        { "en": "polar bear", "pos": "n", "zh": "北極熊" },
        { "en": "snake",    "pos": "n", "zh": "蛇" },
        { "en": "spider",   "pos": "n", "zh": "蜘蛛" },
        { "en": "zebra",    "pos": "n", "zh": "斑馬" }
      ]
    },
    {
      "id": "food",
      "label": "食物 & 飲料",
      "icon": "🍽️",
      "words": [
        { "en": "apple",      "pos": "n", "zh": "蘋果" },
        { "en": "banana",     "pos": "n", "zh": "香蕉" },
        { "en": "pear",       "pos": "n", "zh": "梨子" },
        { "en": "grape",      "pos": "n", "zh": "葡萄" },
        { "en": "watermelon", "pos": "n", "zh": "西瓜" },
        { "en": "lemon",      "pos": "n", "zh": "檸檬" },
        { "en": "lime",       "pos": "n", "zh": "萊姆" },
        { "en": "coconut",    "pos": "n", "zh": "椰子" },
        { "en": "carrot",     "pos": "n", "zh": "紅蘿蔔" },
        { "en": "potato",     "pos": "n", "zh": "馬鈴薯" },
        { "en": "tomato",     "pos": "n", "zh": "番茄" },
        { "en": "egg",        "pos": "n", "zh": "雞蛋" },
        { "en": "rice",       "pos": "n", "zh": "米飯" },
        { "en": "bread",      "pos": "n", "zh": "麵包" },
        { "en": "burger",     "pos": "n", "zh": "漢堡" },
        { "en": "sausage",    "pos": "n", "zh": "香腸" },
        { "en": "meat",       "pos": "n", "zh": "肉" },
        { "en": "meatballs",  "pos": "n", "zh": "肉丸" },
        { "en": "milk",       "pos": "n", "zh": "牛奶" },
        { "en": "juice",      "pos": "n", "zh": "果汁" },
        { "en": "lemonade",   "pos": "n", "zh": "檸檬汁" },
        { "en": "ice cream",  "pos": "n", "zh": "冰淇淋" },
        { "en": "chocolate",  "pos": "n", "zh": "巧克力" },
        { "en": "candy",      "pos": "n", "zh": "糖果" },
        { "en": "sweet(s)",   "pos": "n", "zh": "糖果（英）" },
        { "en": "breakfast",  "pos": "n", "zh": "早餐" },
        { "en": "lunch",      "pos": "n", "zh": "午餐" },
        { "en": "dinner",     "pos": "n", "zh": "晚餐" },
        { "en": "water",      "pos": "n", "zh": "水" },
        { "en": "food",       "pos": "n", "zh": "食物" },
        { "en": "fruit",      "pos": "n", "zh": "水果" },
        { "en": "vegetable",  "pos": "n", "zh": "蔬菜（可自己補）" }
      ]
    },
    {
      "id": "clothes",
      "label": "衣物",
      "icon": "👕",
      "words": [
        { "en": "clothes", "pos": "n", "zh": "衣服（總稱）" },
        { "en": "T-shirt", "pos": "n", "zh": "T 恤" },
        { "en": "shirt",   "pos": "n", "zh": "襯衫" },
        { "en": "skirt",   "pos": "n", "zh": "裙子" },
        { "en": "dress",   "pos": "n", "zh": "洋裝" },
        { "en": "jeans",   "pos": "n", "zh": "牛仔褲" },
        { "en": "shorts",  "pos": "n", "zh": "短褲" },
        { "en": "trousers","pos": "n", "zh": "長褲" },
        { "en": "shoes",   "pos": "n", "zh": "鞋子" },
        { "en": "boots",   "pos": "n", "zh": "靴子" },
        { "en": "sock",    "pos": "n", "zh": "襪子" },
        { "en": "hat",     "pos": "n", "zh": "帽子" },
        { "en": "jacket",  "pos": "n", "zh": "夾克；外套" }
      ]
    },
    {
      "id": "house",
      "label": "房子 & 房間",
      "icon": "🏠",
      "words": [
        { "en": "house",       "pos": "n", "zh": "房子" },
        { "en": "home",        "pos": "n", "zh": "家；家庭" },
        { "en": "room",        "pos": "n", "zh": "房間" },
        { "en": "kitchen",     "pos": "n", "zh": "廚房" },
        { "en": "bedroom",     "pos": "n", "zh": "臥室" },
        { "en": "living room", "pos": "n", "zh": "客廳" },
        { "en": "dining room", "pos": "n", "zh": "餐廳" },
        { "en": "bathroom",    "pos": "n", "zh": "浴室；洗手間" },
        { "en": "door",        "pos": "n", "zh": "門" },
        { "en": "window",      "pos": "n", "zh": "窗戶" },
        { "en": "floor",       "pos": "n", "zh": "地板" },
        { "en": "wall",        "pos": "n", "zh": "牆" },
        { "en": "hall",        "pos": "n", "zh": "走廊；大廳" },
        { "en": "sofa",        "pos": "n", "zh": "沙發" },
        { "en": "table",       "pos": "n", "zh": "桌子" },
        { "en": "chair",       "pos": "n", "zh": "椅子" },
        { "en": "cupboard",    "pos": "n", "zh": "碗櫃；櫥櫃" },
        { "en": "bookcase",    "pos": "n", "zh": "書櫃" },
        { "en": "rug",         "pos": "n", "zh": "小地毯" },
        { "en": "bed",         "pos": "n", "zh": "床" }
      ]
    },
    {
      "id": "school",
      "label": "學校 & 文具",
      "icon": "🏫",
      "words": [
        { "en": "school",   "pos": "n", "zh": "學校" },
        { "en": "class",    "pos": "n", "zh": "班級；課程" },
        { "en": "classroom","pos": "n", "zh": "教室" },
        { "en": "classmate","pos": "n", "zh": "同學" },
        { "en": "teacher",  "pos": "n", "zh": "老師" },
        { "en": "desk",     "pos": "n", "zh": "書桌" },
        { "en": "chair",    "pos": "n", "zh": "椅子" },
        { "en": "board",    "pos": "n", "zh": "黑板／白板" },
        { "en": "board game","pos": "n", "zh": "桌上遊戲" },
        { "en": "book",     "pos": "n", "zh": "書" },
        { "en": "page",     "pos": "n", "zh": "頁；頁面" },
        { "en": "pencil",   "pos": "n", "zh": "鉛筆" },
        { "en": "pen",      "pos": "n", "zh": "原子筆；鋼筆" },
        { "en": "rubber",   "pos": "n", "zh": "橡皮擦（英）" },
        { "en": "eraser",   "pos": "n", "zh": "橡皮擦（美）" },
        { "en": "ruler",    "pos": "n", "zh": "尺" },
        { "en": "crayon",   "pos": "n", "zh": "蠟筆" },
        { "en": "drawing",  "pos": "n", "zh": "圖畫" },
        { "en": "paint",    "pos": "n", "zh": "顏料；油漆" },
        { "en": "painting", "pos": "n", "zh": "畫作" },
        { "en": "sentence", "pos": "n", "zh": "句子" },
        { "en": "letter",   "pos": "n", "zh": "字母；信" },
        { "en": "alphabet", "pos": "n", "zh": "字母表" },
        { "en": "computer", "pos": "n", "zh": "電腦" },
        { "en": "keyboard", "pos": "n", "zh": "鍵盤" },
        { "en": "mouse",    "pos": "n", "zh": "滑鼠" }
      ]
    },
    {
      "id": "sports",
      "label": "運動 & 玩具",
      "icon": "⚽",
      "words": [
        { "en": "game",        "pos": "n", "zh": "遊戲" },
        { "en": "sport",       "pos": "n", "zh": "運動" },
        { "en": "football",    "pos": "n", "zh": "足球" },
        { "en": "soccer",      "pos": "n", "zh": "足球（美）" },
        { "en": "basketball",  "pos": "n", "zh": "籃球" },
        { "en": "tennis",      "pos": "n", "zh": "網球" },
        { "en": "tennis racket","pos": "n", "zh": "網球拍" },
        { "en": "table tennis","pos": "n", "zh": "桌球" },
        { "en": "badminton",   "pos": "n", "zh": "羽毛球" },
        { "en": "hockey",      "pos": "n", "zh": "曲棍球" },
        { "en": "ball",        "pos": "n", "zh": "球" },
        { "en": "bat",         "pos": "n", "zh": "球棒" },
        { "en": "baseball",    "pos": "n", "zh": "棒球" },
        { "en": "baseball cap","pos": "n", "zh": "棒球帽" },
        { "en": "skateboard",  "pos": "n", "zh": "滑板" },
        { "en": "skateboarding","pos": "n", "zh": "滑板運動" },
        { "en": "toy",         "pos": "n", "zh": "玩具" },
        { "en": "doll",        "pos": "n", "zh": "洋娃娃" },
        { "en": "teddy",       "pos": "n", "zh": "泰迪熊" },
        { "en": "balloon",     "pos": "n", "zh": "氣球" },
        { "en": "board game",  "pos": "n", "zh": "桌遊" }
      ]
    },
    {
      "id": "transport",
      "label": "交通工具 & 戶外",
      "icon": "🚗",
      "words": [
        { "en": "car",      "pos": "n", "zh": "汽車" },
        { "en": "bus",      "pos": "n", "zh": "公車" },
        { "en": "bike",     "pos": "n", "zh": "腳踏車" },
        { "en": "motorbike","pos": "n", "zh": "機車" },
        { "en": "lorry",    "pos": "n", "zh": "卡車（英）" },
        { "en": "truck",    "pos": "n", "zh": "卡車（美）" },
        { "en": "train",    "pos": "n", "zh": "火車" },
        { "en": "boat",     "pos": "n", "zh": "小船" },
        { "en": "ship",     "pos": "n", "zh": "船艦" },
        { "en": "plane",    "pos": "n", "zh": "飛機" },
        { "en": "helicopter","pos": "n", "zh": "直升機" },
        { "en": "street",   "pos": "n", "zh": "街道" },
        { "en": "beach",    "pos": "n", "zh": "海灘" },
        { "en": "sea",      "pos": "n", "zh": "海" },
        { "en": "garden",   "pos": "n", "zh": "花園" },
        { "en": "park",     "pos": "n", "zh": "公園" }
      ]
    },
    {
      "id": "actions",
      "label": "動作動詞",
      "icon": "🏃",
      "words": [
        { "en": "be",       "pos": "v", "zh": "是" },
        { "en": "have",     "pos": "v", "zh": "有" },
        { "en": "have got", "pos": "v", "zh": "有（口語）" },
        { "en": "go",       "pos": "v", "zh": "去" },
        { "en": "go to bed","pos": "v", "zh": "去睡覺" },
        { "en": "go to sleep","pos": "v","zh":"入睡" },
        { "en": "come",     "pos": "v", "zh": "來" },
        { "en": "eat",      "pos": "v", "zh": "吃" },
        { "en": "drink",    "pos": "v", "zh": "喝" },
        { "en": "play",     "pos": "v", "zh": "玩；彈奏；踢（球）" },
        { "en": "read",     "pos": "v", "zh": "讀" },
        { "en": "write",    "pos": "v", "zh": "寫" },
        { "en": "draw",     "pos": "v", "zh": "畫畫" },
        { "en": "listen",   "pos": "v", "zh": "聽" },
        { "en": "look",     "pos": "v", "zh": "看" },
        { "en": "look at",  "pos": "v", "zh": "注視" },
        { "en": "learn",    "pos": "v", "zh": "學習" },
        { "en": "talk",     "pos": "v", "zh": "說話" },
        { "en": "say",      "pos": "v", "zh": "說" },
        { "en": "sing",     "pos": "v", "zh": "唱歌" },
        { "en": "stand",    "pos": "v", "zh": "站立" },
        { "en": "sit",      "pos": "v", "zh": "坐下" },
        { "en": "run",      "pos": "v", "zh": "跑" },
        { "en": "swim",     "pos": "v", "zh": "游泳" },
        { "en": "jump",     "pos": "v", "zh": "跳" },
        { "en": "drive",    "pos": "v", "zh": "開（車）" },
        { "en": "fly",      "pos": "v", "zh": "飛" },
        { "en": "open",     "pos": "v", "zh": "打開" },
        { "en": "close",    "pos": "v", "zh": "關閉" },
        { "en": "clean",    "pos": "v", "zh": "打掃；弄乾淨" },
        { "en": "clap",     "pos": "v", "zh": "拍手" },
        { "en": "count",    "pos": "v", "zh": "數數" },
        { "en": "choose",   "pos": "v", "zh": "選擇" },
        { "en": "bounce",   "pos": "v", "zh": "彈跳" },
        { "en": "catch",    "pos": "v", "zh": "接住" },
        { "en": "hit",      "pos": "v", "zh": "打；敲" },
        { "en": "hold",     "pos": "v", "zh": "拿著" },
        { "en": "pick up",  "pos": "v", "zh": "撿起；拿起" },
        { "en": "point",    "pos": "v", "zh": "指" },
        { "en": "show",     "pos": "v", "zh": "展示；給…看" },
        { "en": "start",    "pos": "v", "zh": "開始" },
        { "en": "stop",     "pos": "v", "zh": "停止" },
        { "en": "smile",    "pos": "v", "zh": "微笑" },
        { "en": "sleep",    "pos": "v", "zh": "睡覺" },
        { "en": "take a photo", "pos": "v", "zh": "拍照" },
        { "en": "understand","pos":"v","zh":"理解" },
        { "en": "want",     "pos": "v", "zh": "想要" },
        { "en": "would like","pos":"v","zh":"想要（較客氣）" }
      ]
    },
    {
      "id": "adjectives",
      "label": "形容詞 & 心情",
      "icon": "😊",
      "words": [
        { "en": "happy",     "pos": "adj", "zh": "開心的" },
        { "en": "sad",       "pos": "adj", "zh": "難過的" },
        { "en": "angry",     "pos": "adj", "zh": "生氣的" },
        { "en": "funny",     "pos": "adj", "zh": "好笑的" },
        { "en": "scary",     "pos": "adj", "zh": "可怕的" },
        { "en": "beautiful", "pos": "adj", "zh": "美麗的" },
        { "en": "good",      "pos": "adj", "zh": "好的" },
        { "en": "bad",       "pos": "adj", "zh": "壞的（可自己補）」" },
        { "en": "big",       "pos": "adj", "zh": "大的" },
        { "en": "small",     "pos": "adj", "zh": "小的" },
        { "en": "long",      "pos": "adj", "zh": "長的" },
        { "en": "short",     "pos": "adj", "zh": "短的；矮的" },
        { "en": "old",       "pos": "adj", "zh": "老的；舊的" },
        { "en": "new",       "pos": "adj", "zh": "新的" },
        { "en": "nice",      "pos": "adj", "zh": "好的；親切的" },
        { "en": "ugly",      "pos": "adj", "zh": "醜的" },
        { "en": "cool",      "pos": "adj", "zh": "酷的；很棒的" },
        { "en": "great",     "pos": "adj", "zh": "很棒的" },
        { "en": "fantastic", "pos": "adj", "zh": "超棒的" },
        { "en": "fun",       "pos": "adj", "zh": "有趣的" }
      ]
    },
    {
      "id": "colors",
      "label": "顏色",
      "icon": "🎨",
      "words": [
        { "en": "red",    "pos": "adj", "zh": "紅色的" },
        { "en": "blue",   "pos": "adj", "zh": "藍色的" },
        { "en": "yellow", "pos": "adj", "zh": "黃色的" },
        { "en": "green",  "pos": "adj", "zh": "綠色的" },
        { "en": "black",  "pos": "adj", "zh": "黑色的" },
        { "en": "white",  "pos": "adj", "zh": "白色的" },
        { "en": "brown",  "pos": "adj", "zh": "棕色的" },
        { "en": "purple", "pos": "adj", "zh": "紫色的" },
        { "en": "orange", "pos": "adj", "zh": "橘色的" },
        { "en": "gray",   "pos": "adj", "zh": "灰色的（美）" },
        { "en": "grey",   "pos": "adj", "zh": "灰色的（英）" },
        { "en": "pink",   "pos": "adj", "zh": "粉紅色的" }
      ]
    },
    {
      "id": "time",
      "label": "時間 & 一天",
      "icon": "⏰",
      "words": [
        { "en": "morning", "pos": "n", "zh": "早上" },
        { "en": "afternoon","pos":"n","zh":"下午" },
        { "en": "evening", "pos": "n", "zh": "傍晚；晚上" },
        { "en": "night",   "pos": "n", "zh": "夜晚" },
        { "en": "today",   "pos": "n", "zh": "今天" },
        { "en": "day",     "pos": "n", "zh": "日子；一天" },
        { "en": "year",    "pos": "n", "zh": "年" }
      ]
    },
    {
      "id": "function",
      "label": "代名詞 & 文法小字",
      "icon": "📌",
      "words": [
        { "en": "I",      "pos": "pron", "zh": "我" },
        { "en": "you",    "pos": "pron", "zh": "你；你們" },
        { "en": "he",     "pos": "pron", "zh": "他" },
        { "en": "she",    "pos": "pron", "zh": "她" },
        { "en": "it",     "pos": "pron", "zh": "它" },
        { "en": "we",     "pos": "pron", "zh": "我們" },
        { "en": "they",   "pos": "pron", "zh": "他們；它們" },
        { "en": "me",     "pos": "pron", "zh": "我（受格）" },
        { "en": "him",    "pos": "pron", "zh": "他（受格）" },
        { "en": "her",    "pos": "pron", "zh": "她（受格／形容詞性）" },
        { "en": "them",   "pos": "pron", "zh": "他們；它們（受格）" },
        { "en": "my",     "pos": "poss adj", "zh": "我的" },
        { "en": "your",   "pos": "poss adj", "zh": "你的；你們的" },
        { "en": "his",    "pos": "poss adj", "zh": "他的" },
        { "en": "her",    "pos": "poss adj", "zh": "她的" },
        { "en": "its",    "pos": "poss adj", "zh": "它的" },
        { "en": "our",    "pos": "poss adj", "zh": "我們的" },
        { "en": "their",  "pos": "poss adj", "zh": "他們的；它們的" },
        { "en": "mine",   "pos": "pron", "zh": "我的（名詞）" },
        { "en": "yours",  "pos": "pron", "zh": "你的；你們的（名詞）" },
        { "en": "his",    "pos": "pron", "zh": "他的（名詞）" },
        { "en": "hers",   "pos": "pron", "zh": "她的（名詞）" },
        { "en": "ours",   "pos": "pron", "zh": "我們的（名詞）" },
        { "en": "theirs", "pos": "pron", "zh": "他們的；它們的（名詞）" },
        { "en": "a",      "pos": "det", "zh": "一個（子音開頭前）" },
        { "en": "an",     "pos": "det", "zh": "一個（母音開頭前）" },
        { "en": "the",    "pos": "det", "zh": "這個；那個" },
        { "en": "and",    "pos": "conj","zh": "和；而且" },
        { "en": "but",    "pos": "conj","zh": "但是" },
        { "en": "or",     "pos": "conj","zh": "或者" },
        { "en": "for",    "pos": "prep","zh": "為了；給" },
        { "en": "from",   "pos": "prep","zh": "從" },
        { "en": "in",     "pos": "prep","zh": "在…裡；在…之中" },
        { "en": "on",     "pos": "prep","zh": "在…上" },
        { "en": "under",  "pos": "prep","zh": "在…下" },
        { "en": "behind", "pos": "prep","zh": "在…後面" },
        { "en": "between","pos": "prep","zh": "在…之間" },
        { "en": "next to","pos": "prep","zh": "在…旁邊" },
        { "en": "in front of","pos":"prep","zh":"在…前面" },
        { "en": "with",   "pos": "prep","zh": "和…一起；帶有" },
        { "en": "of",     "pos": "prep","zh": "…的" },
        { "en": "about",  "pos": "prep","zh": "關於" }
      ]
    },
    {
      "id": "questions",
      "label": "問句字 & 句子小字",
      "icon": "❓",
      "words": [
        { "en": "what",     "pos": "int", "zh": "什麼" },
        { "en": "where",    "pos": "int", "zh": "哪裡" },
        { "en": "which",    "pos": "int", "zh": "哪一個" },
        { "en": "who",      "pos": "int", "zh": "誰" },
        { "en": "whose",    "pos": "int", "zh": "誰的" },
        { "en": "how",      "pos": "int", "zh": "怎麼樣" },
        { "en": "how many", "pos": "int", "zh": "多少（可數）" },
        { "en": "how old",  "pos": "int", "zh": "幾歲" },
        { "en": "when",     "pos": "int", "zh": "何時（可自己補）" }
      ]
    },
    {
      "id": "discourse",
      "label": "感嘆 & 句首小字",
      "icon": "💬",
      "words": [
        { "en": "hello!",     "pos": "excl", "zh": "哈囉！" },
        { "en": "hi!",        "pos": "excl", "zh": "嗨！" },
        { "en": "goodbye!",   "pos": "excl", "zh": "再見！" },
        { "en": "bye!",       "pos": "excl", "zh": "掰掰！" },
        { "en": "see you!",   "pos": "excl", "zh": "再見！" },
        { "en": "OK",         "pos": "dis",  "zh": "好；可以" },
        { "en": "oh",         "pos": "dis",  "zh": "喔；啊" },
        { "en": "oh dear!",   "pos": "excl", "zh": "哎呀！" },
        { "en": "wow!",       "pos": "excl", "zh": "哇！" },
        { "en": "hooray!",    "pos": "excl", "zh": "萬歲！太棒了！" },
        { "en": "thank you",  "pos": "dis",  "zh": "謝謝你" },
        { "en": "thanks",     "pos": "dis",  "zh": "謝謝" },
        { "en": "sorry",      "pos": "adj/int", "zh": "對不起" },
        { "en": "don’t worry!","pos": "excl","zh":"別擔心！" },
        { "en": "well done",  "pos": "dis",  "zh": "做得好！" },
        { "en": "please",     "pos": "dis",  "zh": "請" },
        { "en": "me too",     "pos": "dis",  "zh": "我也是" },
        { "en": "so",         "pos": "dis",  "zh": "所以；那麼" }
      ]
    }
      ]
    };

    // Movers：已完整帶入你剛剛要的「主題＋中文＋詞性」版本
    const MOVERS_DATA = {
      "categories": [
        {
          "id": "people_family_names",
          "label": "人物・家庭・名字",
          "icon": "👨‍👩‍👧‍👦",
          "words": [
            { "en": "aunt", "pos": "n", "zh": "阿姨；姑姑；舅媽" },
            { "en": "daughter", "pos": "n", "zh": "女兒" },
            { "en": "granddaughter", "pos": "n", "zh": "孫女" },
            { "en": "grandparent", "pos": "n", "zh": "祖父母" },
            { "en": "grandson", "pos": "n", "zh": "孫子" },
            { "en": "grown-up", "pos": "n", "zh": "大人" },
            { "en": "parent", "pos": "n", "zh": "父母；家長" },
            { "en": "son", "pos": "n", "zh": "兒子" },
            { "en": "uncle", "pos": "n", "zh": "叔叔；舅舅；伯伯" },

            { "en": "Charlie", "pos": "n", "zh": "查理（人名）" },
            { "en": "Clare", "pos": "n", "zh": "克萊兒（人名）" },
            { "en": "Daisy", "pos": "n", "zh": "黛西（人名）" },
            { "en": "Fred", "pos": "n", "zh": "弗雷德（人名）" },
            { "en": "Jack", "pos": "n", "zh": "傑克（人名）" },
            { "en": "Jane", "pos": "n", "zh": "珍（人名）" },
            { "en": "Jim", "pos": "n", "zh": "吉姆（人名）" },
            { "en": "Julia", "pos": "n", "zh": "茱莉亞（人名）" },
            { "en": "Lily", "pos": "n", "zh": "莉莉（人名）" },
            { "en": "Mary", "pos": "n", "zh": "瑪麗（人名）" },
            { "en": "Paul", "pos": "n", "zh": "保羅（人名）" },
            { "en": "Peter", "pos": "n", "zh": "彼得（人名）" },
            { "en": "Sally", "pos": "n", "zh": "莎莉（人名）" },
            { "en": "Vicky", "pos": "n", "zh": "薇琪（人名）" },
            { "en": "Zoe", "pos": "n", "zh": "柔依（人名）" }
          ]
        },
        {
          "id": "jobs_roles",
          "label": "職業・身分",
          "icon": "👩‍⚕️",
          "words": [
            { "en": "dentist", "pos": "n", "zh": "牙醫" },
            { "en": "doctor", "pos": "n", "zh": "醫生" },
            { "en": "farmer", "pos": "n", "zh": "農夫" },
            { "en": "driver", "pos": "n", "zh": "司機；駕駛" },
            { "en": "nurse", "pos": "n", "zh": "護士" },
            { "en": "cook", "pos": "n/v", "zh": "廚師；做飯" },
            { "en": "model", "pos": "n", "zh": "模特兒" },
            { "en": "player", "pos": "n", "zh": "選手；玩家" },
            { "en": "pop star", "pos": "n", "zh": "流行歌手；明星" }
          ]
        },
        {
          "id": "body_health",
          "label": "身體・健康",
          "icon": "🩺",
          "words": [
            { "en": "beard", "pos": "n", "zh": "鬍子（下巴鬍）" },
            { "en": "neck", "pos": "n", "zh": "脖子；頸部" },
            { "en": "stomach", "pos": "n", "zh": "肚子；胃" },
            { "en": "tooth/teeth", "pos": "n", "zh": "牙齒" },

            { "en": "earache", "pos": "n", "zh": "耳朵痛" },
            { "en": "headache", "pos": "n", "zh": "頭痛" },
            { "en": "stomach-ache", "pos": "n", "zh": "胃痛；肚子痛" },
            { "en": "toothache", "pos": "n", "zh": "牙痛" },
            { "en": "cough", "pos": "n", "zh": "咳嗽" },
            { "en": "cold", "pos": "adj/n", "zh": "感冒；冷的" },
            { "en": "hurt", "pos": "v", "zh": "受傷；弄痛" },
            { "en": "ill", "pos": "adj", "zh": "生病的" },
            { "en": "sick", "pos": "adj", "zh": "生病的；想吐的" },
            { "en": "weak", "pos": "adj", "zh": "虛弱的" },
            { "en": "well", "pos": "adj/adv", "zh": "健康的；好地" },
            { "en": "hungry", "pos": "adj", "zh": "餓的" },
            { "en": "thirsty", "pos": "adj", "zh": "口渴的" },

            { "en": "temperature", "pos": "n", "zh": "體溫；溫度" },
            { "en": "hospital", "pos": "n", "zh": "醫院" }
          ]
        },
        {
          "id": "adjectives_feelings",
          "label": "形容詞・心情",
          "icon": "😊",
          "words": [
            { "en": "afraid", "pos": "adj", "zh": "害怕的" },
            { "en": "all right", "pos": "adj/adv", "zh": "還好；沒問題" },
            { "en": "asleep", "pos": "adj", "zh": "睡著的" },
            { "en": "awake", "pos": "adj", "zh": "醒著的" },
            { "en": "bad", "pos": "adj", "zh": "不好的；糟的" },
            { "en": "best", "pos": "adj/adv", "zh": "最好的；最好地" },
            { "en": "better", "pos": "adj/adv", "zh": "比較好；更好地" },
            { "en": "blond(e)", "pos": "adj", "zh": "金髮的" },
            { "en": "boring", "pos": "adj", "zh": "無聊的" },
            { "en": "brave", "pos": "adj", "zh": "勇敢的" },
            { "en": "busy", "pos": "adj", "zh": "忙碌的" },
            { "en": "careful", "pos": "adj", "zh": "小心的" },
            { "en": "clever", "pos": "adj", "zh": "聰明的" },
            { "en": "cold", "pos": "adj/n", "zh": "冷的；感冒" },
            { "en": "curly", "pos": "adj", "zh": "捲曲的" },
            { "en": "dangerous", "pos": "adj", "zh": "危險的" },
            { "en": "different", "pos": "adj", "zh": "不同的" },
            { "en": "difficult", "pos": "adj", "zh": "困難的" },
            { "en": "easy", "pos": "adj", "zh": "容易的" },
            { "en": "exciting", "pos": "adj", "zh": "令人興奮的" },
            { "en": "fair", "pos": "adj", "zh": "公平的；（膚色）白皙的" },
            { "en": "famous", "pos": "adj", "zh": "有名的" },
            { "en": "fat", "pos": "adj", "zh": "胖的" },
            { "en": "frightened", "pos": "adj", "zh": "受到驚嚇的；害怕的" },
            { "en": "hot", "pos": "adj", "zh": "熱的；辣的" },
            { "en": "huge", "pos": "adj", "zh": "巨大的" },
            { "en": "little", "pos": "adj", "zh": "小小的" },
            { "en": "loud", "pos": "adj", "zh": "大聲的" },
            { "en": "naughty", "pos": "adj", "zh": "調皮的；頑皮的" },
            { "en": "pretty", "pos": "adj", "zh": "漂亮的" },
            { "en": "quick", "pos": "adj", "zh": "快速的" },
            { "en": "quiet", "pos": "adj", "zh": "安靜的" },
            { "en": "safe", "pos": "adj", "zh": "安全的" },
            { "en": "slow", "pos": "adj", "zh": "慢的" },
            { "en": "straight", "pos": "adj", "zh": "直的" },
            { "en": "strong", "pos": "adj", "zh": "強壯的；強烈的" },
            { "en": "sunny", "pos": "adj", "zh": "晴朗的；陽光充足的" },
            { "en": "surprised", "pos": "adj", "zh": "驚訝的" },
            { "en": "sweet", "pos": "adj", "zh": "甜的；甜蜜的" },
            { "en": "tall", "pos": "adj", "zh": "高的" },
            { "en": "terrible", "pos": "adj", "zh": "可怕的；糟糕的" },
            { "en": "thin", "pos": "adj", "zh": "瘦的；薄的" },
            { "en": "tired", "pos": "adj", "zh": "累的" },
            { "en": "wet", "pos": "adj", "zh": "濕的" },
            { "en": "weak", "pos": "adj", "zh": "虛弱的" },
            { "en": "wrong", "pos": "adj", "zh": "錯誤的" },
            { "en": "worse", "pos": "adj/adv", "zh": "更糟的；更糟地" },
            { "en": "worst", "pos": "adj/adv", "zh": "最糟的；最糟地" }
          ]
        },
        {
          "id": "animals",
          "label": "動物",
          "icon": "🐾",
          "words": [
            { "en": "bat", "pos": "n", "zh": "蝙蝠" },
            { "en": "dolphin", "pos": "n", "zh": "海豚" },
            { "en": "kangaroo", "pos": "n", "zh": "袋鼠" },
            { "en": "kitten", "pos": "n", "zh": "小貓" },
            { "en": "lion", "pos": "n", "zh": "獅子" },
            { "en": "panda", "pos": "n", "zh": "熊貓" },
            { "en": "parrot", "pos": "n", "zh": "鸚鵡" },
            { "en": "penguin", "pos": "n", "zh": "企鵝" },
            { "en": "puppy", "pos": "n", "zh": "小狗" },
            { "en": "rabbit", "pos": "n", "zh": "兔子" },
            { "en": "shark", "pos": "n", "zh": "鯊魚" },
            { "en": "snail", "pos": "n", "zh": "蝸牛" },
            { "en": "whale", "pos": "n", "zh": "鯨魚" }
          ]
        },
        {
          "id": "food_drink",
          "label": "食物・飲料",
          "icon": "🍽️",
          "words": [
            { "en": "cheese", "pos": "n", "zh": "起司；乳酪" },
            { "en": "coffee", "pos": "n", "zh": "咖啡" },
            { "en": "ice", "pos": "n", "zh": "冰；冰塊" },
            { "en": "milkshake", "pos": "n", "zh": "奶昔" },
            { "en": "noodles", "pos": "n", "zh": "麵條" },
            { "en": "pancake", "pos": "n", "zh": "煎餅；鬆餅" },
            { "en": "pasta", "pos": "n", "zh": "義大利麵" },
            { "en": "salad", "pos": "n", "zh": "沙拉" },
            { "en": "sandwich", "pos": "n", "zh": "三明治" },
            { "en": "sauce", "pos": "n", "zh": "醬汁" },
            { "en": "soup", "pos": "n", "zh": "湯" },
            { "en": "tea", "pos": "n", "zh": "茶" },
            { "en": "vegetable", "pos": "n", "zh": "蔬菜" },

            { "en": "bottle", "pos": "n", "zh": "瓶子" },
            { "en": "bowl", "pos": "n", "zh": "碗" },
            { "en": "cup", "pos": "n", "zh": "杯子" },
            { "en": "plate", "pos": "n", "zh": "盤子" }
          ]
        },
        {
          "id": "home_buildings",
          "label": "家裡・建築物",
          "icon": "🏠",
          "words": [
            { "en": "address", "pos": "n", "zh": "地址" },
            { "en": "balcony", "pos": "n", "zh": "陽台" },
            { "en": "basement", "pos": "n", "zh": "地下室" },
            { "en": "blanket", "pos": "n", "zh": "毯子；毛毯" },
            { "en": "building", "pos": "n", "zh": "建築物" },
            { "en": "floor", "pos": "n", "zh": "樓層；地板" },
            { "en": "glass", "pos": "n", "zh": "玻璃杯；玻璃" },
            { "en": "roof", "pos": "n", "zh": "屋頂" },
            { "en": "seat", "pos": "n", "zh": "座位" },
            { "en": "shower", "pos": "n", "zh": "淋浴；蓮蓬頭" },
            { "en": "stair(s)", "pos": "n", "zh": "樓梯" },
            { "en": "towel", "pos": "n", "zh": "毛巾" },
            { "en": "downstairs", "pos": "adv/n", "zh": "在樓下；樓下" },
            { "en": "upstairs", "pos": "adv/n", "zh": "在樓上；樓上" },
            { "en": "lift", "pos": "n", "zh": "電梯（英）" },
            { "en": "elevator", "pos": "n", "zh": "電梯（美）" }
          ]
        },
        {
          "id": "places_town",
          "label": "城市裡的地方",
          "icon": "🏙️",
          "words": [
            { "en": "bus station", "pos": "n", "zh": "巴士站；客運站" },
            { "en": "bus stop", "pos": "n", "zh": "公車站牌" },
            { "en": "café", "pos": "n", "zh": "咖啡館" },
            { "en": "car park", "pos": "n", "zh": "停車場（英）" },
            { "en": "cinema", "pos": "n", "zh": "電影院" },
            { "en": "circus", "pos": "n", "zh": "馬戲團" },
            { "en": "city", "pos": "n", "zh": "城市" },
            { "en": "city/town centre", "pos": "n", "zh": "市中心；鬧區" },
            { "en": "funfair", "pos": "n", "zh": "遊樂園；嘉年華遊樂場" },
            { "en": "hospital", "pos": "n", "zh": "醫院" },
            { "en": "library", "pos": "n", "zh": "圖書館" },
            { "en": "market", "pos": "n", "zh": "市場" },
            { "en": "shopping centre", "pos": "n", "zh": "購物中心（英）" },
            { "en": "sports centre", "pos": "n", "zh": "運動中心" },
            { "en": "square", "pos": "adj/n", "zh": "方形的；廣場" },
            { "en": "station", "pos": "n", "zh": "車站" },
            { "en": "supermarket", "pos": "n", "zh": "超級市場" },
            { "en": "swimming pool", "pos": "n", "zh": "游泳池" },
            { "en": "town", "pos": "n", "zh": "鎮；小城市" },
            { "en": "town/city centre", "pos": "n", "zh": "鎮中心／市中心" },
            { "en": "village", "pos": "n", "zh": "村莊" }
          ]
        },
        {
          "id": "nature_world_weather",
          "label": "自然・世界・天氣",
          "icon": "⛰️",
          "words": [
            { "en": "country", "pos": "n", "zh": "國家；鄉間" },
            { "en": "countryside", "pos": "n", "zh": "鄉下；鄉間" },
            { "en": "farm", "pos": "n", "zh": "農場" },
            { "en": "field", "pos": "n", "zh": "田地；場地" },
            { "en": "forest", "pos": "n", "zh": "森林" },
            { "en": "grass", "pos": "n", "zh": "草；草地" },
            { "en": "ground", "pos": "n", "zh": "地面" },
            { "en": "island", "pos": "n", "zh": "島嶼" },
            { "en": "jungle", "pos": "n", "zh": "叢林" },
            { "en": "lake", "pos": "n", "zh": "湖" },
            { "en": "leaf/leaves", "pos": "n", "zh": "葉子／葉子（複數）" },
            { "en": "moon", "pos": "n", "zh": "月亮" },
            { "en": "mountain", "pos": "n", "zh": "山" },
            { "en": "rainbow", "pos": "n", "zh": "彩虹" },
            { "en": "river", "pos": "n", "zh": "河流" },
            { "en": "rock", "pos": "n", "zh": "岩石；石頭" },
            { "en": "sky", "pos": "n", "zh": "天空" },
            { "en": "star", "pos": "n", "zh": "星星" },
            { "en": "waterfall", "pos": "n", "zh": "瀑布" },
            { "en": "world", "pos": "n", "zh": "世界" },

            { "en": "cloud", "pos": "n", "zh": "雲" },
            { "en": "cloudy", "pos": "adj", "zh": "多雲的" },
            { "en": "rain", "pos": "n/v", "zh": "雨；下雨" },
            { "en": "snow", "pos": "n/v", "zh": "雪；下雪" },
            { "en": "weather", "pos": "n", "zh": "天氣" },
            { "en": "wind", "pos": "n", "zh": "風" },
            { "en": "windy", "pos": "adj", "zh": "有風的；風大的" }
          ]
        },
        {
          "id": "media_tech_school",
          "label": "媒體・科技・學習",
          "icon": "💻",
          "words": [
            { "en": "app", "pos": "n", "zh": "應用程式；APP" },
            { "en": "band", "pos": "n", "zh": "樂團" },
            { "en": "CD", "pos": "n", "zh": "光碟" },
            { "en": "comic", "pos": "n", "zh": "漫畫" },
            { "en": "comic book", "pos": "n", "zh": "漫畫書" },
            { "en": "DVD", "pos": "n", "zh": "DVD 光碟" },
            { "en": "e-book", "pos": "n", "zh": "電子書" },
            { "en": "email", "pos": "n/v", "zh": "電子郵件；寄電郵" },
            { "en": "film", "pos": "n/v", "zh": "電影；拍攝影片" },
            { "en": "film star", "pos": "n", "zh": "電影明星" },
            { "en": "internet", "pos": "n", "zh": "網際網路" },
            { "en": "laptop", "pos": "n", "zh": "筆記型電腦" },
            { "en": "machine", "pos": "n", "zh": "機器" },
            { "en": "map", "pos": "n", "zh": "地圖" },
            { "en": "message", "pos": "n", "zh": "訊息" },
            { "en": "model", "pos": "n", "zh": "模特兒；模型" },
            { "en": "movie", "pos": "n", "zh": "電影" },
            { "en": "practice", "pos": "n", "zh": "練習（名詞）" },
            { "en": "practise", "pos": "v", "zh": "練習（動詞）" },
            { "en": "text", "pos": "n/v", "zh": "文字訊息；傳簡訊" },
            { "en": "video", "pos": "n/v", "zh": "影片；錄影" },
            { "en": "website", "pos": "n", "zh": "網站" },
            { "en": "homework", "pos": "n", "zh": "家庭作業" },
            { "en": "library", "pos": "n", "zh": "圖書館" }
          ]
        },
        {
          "id": "free_time_sports",
          "label": "休閒・運動・遊樂",
          "icon": "⚽",
          "words": [
            { "en": "dance", "pos": "n/v", "zh": "舞蹈；跳舞" },
            { "en": "dress up", "pos": "v", "zh": "裝扮；變裝" },
            { "en": "funfair", "pos": "n", "zh": "遊樂園；嘉年華遊樂場" },
            { "en": "go shopping", "pos": "v", "zh": "逛街購物" },
            { "en": "holiday", "pos": "n", "zh": "假期" },
            { "en": "party", "pos": "n", "zh": "派對" },
            { "en": "picnic", "pos": "n", "zh": "野餐" },
            { "en": "trip", "pos": "n", "zh": "旅行；短途旅程" },
            { "en": "treasure", "pos": "n", "zh": "寶藏" },

            { "en": "goal", "pos": "n", "zh": "進球；球門" },
            { "en": "kick", "pos": "n", "zh": "踢（名詞）" },
            { "en": "ride", "pos": "n", "zh": "乘坐；遊樂設施的一趟" },
            { "en": "roller skates", "pos": "n", "zh": "輪鞋；直排輪鞋" },
            { "en": "roller skating", "pos": "n", "zh": "溜直排輪；溜冰" },
            { "en": "sail", "pos": "n/v", "zh": "帆；航行" },
            { "en": "score", "pos": "v", "zh": "得分" },
            { "en": "skate", "pos": "n/v", "zh": "溜冰鞋；溜冰" },
            { "en": "skip", "pos": "v", "zh": "跳繩；蹦跳" },
            { "en": "swim", "pos": "n/v", "zh": "游泳；游一次" },
            { "en": "swimming pool", "pos": "n", "zh": "游泳池" },
            { "en": "swimsuit", "pos": "n", "zh": "泳衣" },
            { "en": "walk", "pos": "n", "zh": "散步；走路（名詞）" }
          ]
        },
        {
          "id": "transport_travel",
          "label": "交通・旅行",
          "icon": "🚗",
          "words": [
            { "en": "bus station", "pos": "n", "zh": "巴士站；客運站" },
            { "en": "bus stop", "pos": "n", "zh": "公車站" },
            { "en": "car park", "pos": "n", "zh": "停車場" },
            { "en": "road", "pos": "n", "zh": "道路" },
            { "en": "ride", "pos": "n", "zh": "搭乘；乘車" },
            { "en": "station", "pos": "n", "zh": "車站" },
            { "en": "ticket", "pos": "n", "zh": "票；車票" },
            { "en": "tractor", "pos": "n", "zh": "拖拉機" },
            { "en": "travel", "pos": "v", "zh": "旅行" },
            { "en": "trip", "pos": "n", "zh": "旅行；旅程" },

            { "en": "catch", "pos": "v", "zh": "趕上（車、船、飛機）" },
            { "en": "get off", "pos": "v", "zh": "下車" },
            { "en": "get on", "pos": "v", "zh": "上車" }
          ]
        },
        {
          "id": "time_days_numbers",
          "label": "時間・星期・數字",
          "icon": "⏰",
          "words": [
            { "en": "after", "pos": "prep", "zh": "在…之後" },
            { "en": "before", "pos": "prep", "zh": "在…之前" },
            { "en": "age", "pos": "n", "zh": "年齡" },
            { "en": "always", "pos": "adv", "zh": "總是；永遠" },
            { "en": "never", "pos": "adv", "zh": "從不；從來沒有" },
            { "en": "often", "pos": "adv", "zh": "經常" },
            { "en": "sometimes", "pos": "adv", "zh": "有時候" },
            { "en": "o’clock", "pos": "adv", "zh": "…點鐘" },
            { "en": "last", "pos": "adj/adv", "zh": "上一個的；最後；上一次" },
            { "en": "then", "pos": "adv", "zh": "然後；那時候" },
            { "en": "yesterday", "pos": "adv/n", "zh": "昨天" },

            { "en": "Monday", "pos": "n", "zh": "星期一" },
            { "en": "Tuesday", "pos": "n", "zh": "星期二" },
            { "en": "Wednesday", "pos": "n", "zh": "星期三" },
            { "en": "Thursday", "pos": "n", "zh": "星期四" },
            { "en": "Friday", "pos": "n", "zh": "星期五" },
            { "en": "Saturday", "pos": "n", "zh": "星期六" },
            { "en": "Sunday", "pos": "n", "zh": "星期日" },
            { "en": "week", "pos": "n", "zh": "一週" },
            { "en": "weekend", "pos": "n", "zh": "週末" },

            { "en": "first", "pos": "adj/adv", "zh": "第一；首先" },
            { "en": "second", "pos": "adj/adv", "zh": "第二" },
            { "en": "third", "pos": "adj/adv", "zh": "第三" },
            { "en": "hundred", "pos": "n", "zh": "一百" }
          ]
        },
        {
          "id": "actions",
          "label": "一般動作動詞",
          "icon": "🏃",
          "words": [
            { "en": "be called", "pos": "v", "zh": "叫做；名為" },
            { "en": "bring", "pos": "v", "zh": "帶來" },
            { "en": "build", "pos": "v", "zh": "建造" },
            { "en": "buy", "pos": "v", "zh": "買" },
            { "en": "call", "pos": "v", "zh": "打電話；稱呼" },
            { "en": "carry", "pos": "v", "zh": "拿；提；搬運" },
            { "en": "catch", "pos": "v", "zh": "抓住；趕上（車）" },
            { "en": "change", "pos": "v", "zh": "改變；更換" },
            { "en": "climb", "pos": "v", "zh": "攀爬；爬上" },
            { "en": "cry", "pos": "v", "zh": "哭" },
            { "en": "dream", "pos": "n/v", "zh": "夢；做夢" },
            { "en": "drive", "pos": "n", "zh": "兜風；開車行程" },
            { "en": "drop", "pos": "v", "zh": "掉落；丟下" },
            { "en": "dry", "pos": "adj/v", "zh": "乾的；弄乾" },
            { "en": "fall", "pos": "v", "zh": "跌倒；掉下" },
            { "en": "feed", "pos": "v", "zh": "餵食" },
            { "en": "fix", "pos": "v", "zh": "修理" },
            { "en": "get dressed", "pos": "v", "zh": "穿好衣服" },
            { "en": "get off", "pos": "v", "zh": "下車；下來" },
            { "en": "get on", "pos": "v", "zh": "上車；上去" },
            { "en": "get undressed", "pos": "v", "zh": "脫衣服" },
            { "en": "get up", "pos": "v", "zh": "起床；起來" },
            { "en": "go shopping", "pos": "v", "zh": "去逛街；買東西" },
            { "en": "grow", "pos": "v", "zh": "生長；長大" },
            { "en": "have (got) to", "pos": "v", "zh": "必須；得要" },
            { "en": "help", "pos": "v", "zh": "幫助" },
            { "en": "hide", "pos": "v", "zh": "躲藏；藏起來" },
            { "en": "hop", "pos": "v", "zh": "單腳跳；蹦跳" },
            { "en": "invite", "pos": "v", "zh": "邀請" },
            { "en": "laugh", "pos": "n/v", "zh": "笑；笑聲" },
            { "en": "look for", "pos": "v", "zh": "尋找" },
            { "en": "lose", "pos": "v", "zh": "失去；丟失；輸" },
            { "en": "mean", "pos": "v", "zh": "意思是；意指" },
            { "en": "move", "pos": "v", "zh": "移動；搬家" },
            { "en": "need", "pos": "v", "zh": "需要" },
            { "en": "plant", "pos": "n/v", "zh": "植物；種植" },
            { "en": "put on", "pos": "v", "zh": "穿上；戴上" },
            { "en": "rain", "pos": "n/v", "zh": "雨；下雨" },
            { "en": "sail", "pos": "n/v", "zh": "帆；航行" },
            { "en": "send", "pos": "v", "zh": "寄；送出" },
            { "en": "shall", "pos": "v", "zh": "將要；要不要…（提議）" },
            { "en": "shop", "pos": "v", "zh": "購物" },
            { "en": "shout", "pos": "v", "zh": "大叫；喊叫" },
            { "en": "skate", "pos": "n/v", "zh": "溜冰鞋；溜冰" },
            { "en": "skip", "pos": "v", "zh": "跳躍；跳繩" },
            { "en": "snow", "pos": "n/v", "zh": "雪；下雪" },
            { "en": "swim", "pos": "n/v", "zh": "游泳；游一次" },
            { "en": "take", "pos": "v", "zh": "拿；帶；搭乘" },
            { "en": "take off", "pos": "v", "zh": "脫下（衣物）；起飛" },
            { "en": "teach", "pos": "v", "zh": "教" },
            { "en": "think", "pos": "v", "zh": "想；認為" },
            { "en": "travel", "pos": "v", "zh": "旅行" },
            { "en": "wait", "pos": "v", "zh": "等待" },
            { "en": "wake (up)", "pos": "v", "zh": "醒來；叫醒" },
            { "en": "walk", "pos": "n/v", "zh": "走路；散步" },
            { "en": "wash", "pos": "n/v", "zh": "洗；洗滌" },
            { "en": "water", "pos": "v", "zh": "澆水" },
            { "en": "wave", "pos": "n/v", "zh": "揮手；波浪" },
            { "en": "work", "pos": "n/v", "zh": "工作；工作（動詞）" },
            { "en": "must", "pos": "v", "zh": "必須" },
            { "en": "could", "pos": "v", "zh": "可以；能（can 的過去式）" },
            { "en": "would", "pos": "v", "zh": "將會；會（假設、禮貌用法）" }
          ]
        },
        {
          "id": "grammar_function",
          "label": "文法小字・介系詞・問句字",
          "icon": "📌",
          "words": [
            { "en": "above", "pos": "prep", "zh": "在…上方" },
            { "en": "after", "pos": "prep", "zh": "在…之後" },
            { "en": "along", "pos": "prep", "zh": "沿著" },
            { "en": "around", "pos": "prep", "zh": "在…周圍；大約" },
            { "en": "at", "pos": "prep", "zh": "在…（時間／地點）" },
            { "en": "before", "pos": "prep", "zh": "在…之前" },
            { "en": "below", "pos": "prep", "zh": "在…下面" },
            { "en": "by", "pos": "prep", "zh": "在…旁；藉由；到…之前" },
            { "en": "down", "pos": "adv/prep", "zh": "往下；在…下方" },
            { "en": "inside", "pos": "adv/n/prep", "zh": "在裡面；裡面；在…裡" },
            { "en": "into", "pos": "prep", "zh": "進入…" },
            { "en": "near", "pos": "adv/prep", "zh": "在附近；靠近…" },
            { "en": "off", "pos": "adv/prep", "zh": "關掉；離開…" },
            { "en": "on", "pos": "adv/prep", "zh": "在…上；在…（某天）" },
            { "en": "opposite", "pos": "prep", "zh": "在…對面" },
            { "en": "out", "pos": "adv", "zh": "在外面；出去" },
            { "en": "out of", "pos": "prep", "zh": "從…裡出來；不在…" },
            { "en": "outside", "pos": "adv/n/prep", "zh": "在外面；外面；在…外面" },
            { "en": "round", "pos": "adj/adv/prep", "zh": "圓的；繞一圈；圍繞…" },
            { "en": "up", "pos": "adv/prep", "zh": "向上；在…上方" },

            { "en": "all", "pos": "adj/adv/det/pron", "zh": "全部的；全部；所有人／東西" },
            { "en": "another", "pos": "det/pron", "zh": "另一個；另外一個" },
            { "en": "any", "pos": "det/pron", "zh": "任何；一些（否定／疑問）" },
            { "en": "every", "pos": "det", "zh": "每一個" },
            { "en": "everyone", "pos": "pron", "zh": "每個人" },
            { "en": "everything", "pos": "pron", "zh": "每件事；一切" },
            { "en": "someone", "pos": "pron", "zh": "某人" },
            { "en": "something", "pos": "pron", "zh": "某件事；某物" },
            { "en": "nothing", "pos": "pron", "zh": "沒有任何東西；什麼也沒有" },
            { "en": "both", "pos": "det/pron", "zh": "兩者；兩個都" },
            { "en": "more", "pos": "adv/det/pron", "zh": "更多；更…" },
            { "en": "most", "pos": "adv/det/pron", "zh": "最多；大多數" },
            { "en": "only", "pos": "adv", "zh": "只；只有" },
            { "en": "pair", "pos": "n", "zh": "一雙；一對" },

            { "en": "how", "pos": "adv", "zh": "怎麼；如何" },
            { "en": "how much", "pos": "adv/int", "zh": "多少（不可數）；多少錢" },
            { "en": "how often", "pos": "adv/int", "zh": "多久一次；多常" },
            { "en": "when", "pos": "adv/conj/int", "zh": "什麼時候；當…的時候" },
            { "en": "where", "pos": "pron", "zh": "在哪裡" },
            { "en": "which", "pos": "pron", "zh": "哪一個" },
            { "en": "who", "pos": "pron", "zh": "誰" },
            { "en": "why", "pos": "int", "zh": "為什麼" },

            { "en": "because", "pos": "conj", "zh": "因為" },
            { "en": "than", "pos": "conj/prep", "zh": "比…" },

            { "en": "badly", "pos": "adv", "zh": "很糟地；不好地" },
            { "en": "carefully", "pos": "adv", "zh": "小心地" },
            { "en": "loudly", "pos": "adv", "zh": "大聲地" },
            { "en": "quickly", "pos": "adv", "zh": "迅速地" },
            { "en": "quietly", "pos": "adv", "zh": "安靜地；小小聲地" },
            { "en": "slowly", "pos": "adv", "zh": "慢慢地" },

            { "en": "come on!", "pos": "excl", "zh": "快一點！加油！" },
            { "en": "excuse me", "pos": "dis", "zh": "不好意思；打擾一下" },
            { "en": "fine", "pos": "adj/excl", "zh": "好的；行；好吧" },
            { "en": "brilliant", "pos": "adj/excl", "zh": "好棒；太厲害了" }
          ]
        }
      ]
    };

    // Flyers 先保留空結構，之後再補
    const FLYERS_DATA = {
  "categories": [
    {
      "id": "people_family_names",
      "label": "人物・家庭・名字",
      "icon": "👨‍👩‍👧‍👦",
      "words": [
        { "en": "anyone", "pos": "pron", "zh": "任何人" },
        { "en": "no-one", "pos": "pron", "zh": "沒有人" },
        { "en": "anybody", "pos": "pron", "zh": "任何人（如有出現）" },
        { "en": "businessman/woman", "pos": "n", "zh": "生意人；商人" },
        { "en": "journalist", "pos": "n", "zh": "記者" },
        { "en": "passenger", "pos": "n", "zh": "乘客" },
        { "en": "police officer", "pos": "n", "zh": "警官" },
        { "en": "singer", "pos": "n", "zh": "歌手" },
        { "en": "student", "pos": "n", "zh": "學生" },
        { "en": "waiter", "pos": "n", "zh": "服務生（男）" },
        { "en": "astronaut", "pos": "n", "zh": "太空人" },
        { "en": "artist", "pos": "n", "zh": "藝術家" },
        { "en": "actor", "pos": "n", "zh": "男演員" },
        { "en": "engineer", "pos": "n", "zh": "工程師" },
        { "en": "designer", "pos": "n", "zh": "設計師" },
        { "en": "mechanic", "pos": "n", "zh": "機械師；修車工" },
        { "en": "photographer", "pos": "n", "zh": "攝影師" },
        { "en": "pilot", "pos": "n", "zh": "飛行員" },
        { "en": "husband", "pos": "n", "zh": "丈夫" },
        { "en": "wife", "pos": "n", "zh": "妻子" },

        { "en": "Betty", "pos": "n", "zh": "貝蒂（人名）" },
        { "en": "David", "pos": "n", "zh": "大衛（人名）" },
        { "en": "Emma", "pos": "n", "zh": "艾瑪（人名）" },
        { "en": "Frank", "pos": "n", "zh": "法蘭克（人名）" },
        { "en": "George", "pos": "n", "zh": "喬治（人名）" },
        { "en": "Harry", "pos": "n", "zh": "哈利（人名）" },
        { "en": "Helen", "pos": "n", "zh": "海倫（人名）" },
        { "en": "Holly", "pos": "n", "zh": "荷莉（人名）" },
        { "en": "Katy", "pos": "n", "zh": "凱蒂（人名）" },
        { "en": "Michael", "pos": "n", "zh": "麥可（人名）" },
        { "en": "Oliver", "pos": "n", "zh": "奧利佛（人名）" },
        { "en": "Richard", "pos": "n", "zh": "理查（人名）" },
        { "en": "Robert", "pos": "n", "zh": "羅伯特（人名）" },
        { "en": "Sarah", "pos": "n", "zh": "莎拉（人名）" },
        { "en": "Sophia", "pos": "n", "zh": "蘇菲亞（人名）" },
        { "en": "William", "pos": "n", "zh": "威廉（人名）" }
      ]
    },
    {
      "id": "jobs_roles",
      "label": "職業・身分",
      "icon": "👩‍⚕️",
      "words": [
        { "en": "actor", "pos": "n", "zh": "演員" },
        { "en": "artist", "pos": "n", "zh": "藝術家" },
        { "en": "astronaut", "pos": "n", "zh": "太空人" },
        { "en": "businessman/woman", "pos": "n", "zh": "生意人；商人" },
        { "en": "designer", "pos": "n", "zh": "設計師" },
        { "en": "engineer", "pos": "n", "zh": "工程師" },
        { "en": "fire fighter", "pos": "n", "zh": "消防員" },
        { "en": "journalist", "pos": "n", "zh": "記者" },
        { "en": "mechanic", "pos": "n", "zh": "機械師；修車工" },
        { "en": "photographer", "pos": "n", "zh": "攝影師" },
        { "en": "pilot", "pos": "n", "zh": "飛行員" },
        { "en": "police officer", "pos": "n", "zh": "警官" },
        { "en": "singer", "pos": "n", "zh": "歌手" },
        { "en": "student", "pos": "n", "zh": "學生" },
        { "en": "waiter", "pos": "n", "zh": "服務生（男）" },
        { "en": "manager", "pos": "n", "zh": "經理" }
      ]
    },
    {
      "id": "body_health",
      "label": "身體・健康",
      "icon": "🩺",
      "words": [
        { "en": "bandage", "pos": "n", "zh": "繃帶" },
        { "en": "burn", "pos": "v", "zh": "燒傷；燙傷；燃燒" },
        { "en": "cut", "pos": "v", "zh": "割傷；切割" },
        { "en": "elbow", "pos": "n", "zh": "手肘" },
        { "en": "finger", "pos": "n", "zh": "手指" },
        { "en": "fur", "pos": "n", "zh": "（動物）皮毛" },
        { "en": "furry", "pos": "adj", "zh": "毛茸茸的" },
        { "en": "sore", "pos": "adj", "zh": "痠痛的" },
        { "en": "medicine", "pos": "n", "zh": "藥；藥物" },
        { "en": "ambulance", "pos": "n", "zh": "救護車" },
        { "en": "x-ray", "pos": "n", "zh": "X 光" },
        { "en": "worried", "pos": "adj", "zh": "擔心的" },
        { "en": "empty", "pos": "adj", "zh": "空的" },
        { "en": "full", "pos": "adj", "zh": "滿的；吃飽的" },
        { "en": "heavy", "pos": "adj", "zh": "重的" },
        { "en": "high", "pos": "adj", "zh": "高的" },
        { "en": "low", "pos": "adj", "zh": "低的" }
      ]
    },
    {
      "id": "adjectives_feelings",
      "label": "形容詞・心情",
      "icon": "😊",
      "words": [
        { "en": "alone", "pos": "adj", "zh": "獨自的；孤單的" },
        { "en": "amazing", "pos": "adj", "zh": "令人驚奇的；太棒了" },
        { "en": "bored", "pos": "adj", "zh": "無聊的" },
        { "en": "broken", "pos": "adj", "zh": "壞掉的；破掉的" },
        { "en": "cheap", "pos": "adj", "zh": "便宜的" },
        { "en": "dark", "pos": "adj", "zh": "黑暗的" },
        { "en": "deep", "pos": "adj", "zh": "深的" },
        { "en": "delicious", "pos": "adj", "zh": "好吃的；美味的" },
        { "en": "early", "pos": "adj/adv", "zh": "早的；早地" },
        { "en": "empty", "pos": "adj", "zh": "空的" },
        { "en": "enormous", "pos": "adj", "zh": "巨大的" },
        { "en": "enough", "pos": "adj/pron", "zh": "足夠的；足夠" },
        { "en": "excellent", "pos": "adj", "zh": "極好的；棒極了" },
        { "en": "excited", "pos": "adj", "zh": "興奮的" },
        { "en": "expensive", "pos": "adj", "zh": "昂貴的" },
        { "en": "fast", "pos": "adj/adv", "zh": "快的；快速地" },
        { "en": "friendly", "pos": "adj", "zh": "友善的" },
        { "en": "frightening", "pos": "adj", "zh": "可怕的；嚇人的" },
        { "en": "hard", "pos": "adj/adv", "zh": "硬的；努力地；困難的" },
        { "en": "horrible", "pos": "adj", "zh": "可怕的；很糟的" },
        { "en": "hungry", "pos": "adj", "zh": "餓的" },
        { "en": "interested", "pos": "adj", "zh": "有興趣的" },
        { "en": "interesting", "pos": "adj", "zh": "有趣的" },
        { "en": "important", "pos": "adj", "zh": "重要的" },
        { "en": "kind", "pos": "adj", "zh": "親切的；和善的" },
        { "en": "large", "pos": "adj", "zh": "大的" },
        { "en": "late", "pos": "adj/adv", "zh": "遲到的；晚地" },
        { "en": "lazy", "pos": "adj", "zh": "懶惰的" },
        { "en": "lovely", "pos": "adj", "zh": "可愛的；美好的" },
        { "en": "lucky", "pos": "adj", "zh": "幸運的" },
        { "en": "missing", "pos": "adj", "zh": "不見的；失蹤的" },
        { "en": "modern", "pos": "adj", "zh": "現代的（如有出現）" },
        { "en": "noisy", "pos": "adj", "zh": "吵鬧的" },
        { "en": "poor", "pos": "adj", "zh": "貧窮的；可憐的" },
        { "en": "pleased", "pos": "adj", "zh": "高興的；滿意的" },
        { "en": "ready", "pos": "adj", "zh": "準備好的" },
        { "en": "rich", "pos": "adj", "zh": "有錢的" },
        { "en": "same", "pos": "adj", "zh": "相同的" },
        { "en": "soft", "pos": "adj", "zh": "柔軟的" },
        { "en": "special", "pos": "adj", "zh": "特別的" },
        { "en": "strange", "pos": "adj", "zh": "奇怪的" },
        { "en": "sure", "pos": "adj", "zh": "確定的" },
        { "en": "unfriendly", "pos": "adj", "zh": "不友善的" },
        { "en": "unhappy", "pos": "adj", "zh": "不快樂的" },
        { "en": "unkind", "pos": "adj", "zh": "不親切的" },
        { "en": "untidy", "pos": "adj", "zh": "不整齊的；亂七八糟的" },
        { "en": "unusual", "pos": "adj", "zh": "不尋常的" },
        { "en": "warm", "pos": "adj", "zh": "溫暖的" },
        { "en": "wild", "pos": "adj", "zh": "野生的；瘋狂的" },
        { "en": "wonderful", "pos": "adj", "zh": "太棒的；精彩的" },
        { "en": "worried", "pos": "adj", "zh": "擔心的" }
      ]
    },
    {
      "id": "animals",
      "label": "動物",
      "icon": "🐾",
      "words": [
        { "en": "beetle", "pos": "n", "zh": "甲蟲" },
        { "en": "butterfly", "pos": "n", "zh": "蝴蝶" },
        { "en": "camel", "pos": "n", "zh": "駱駝" },
        { "en": "dinosaur", "pos": "n", "zh": "恐龍" },
        { "en": "eagle", "pos": "n", "zh": "老鷹" },
        { "en": "insect", "pos": "n", "zh": "昆蟲" },
        { "en": "octopus", "pos": "n", "zh": "章魚" },
        { "en": "swan", "pos": "n", "zh": "天鵝" },
        { "en": "tortoise", "pos": "n", "zh": "陸龜" }
      ]
    },
    {
      "id": "food_drink",
      "label": "食物・飲料",
      "icon": "🍽️",
      "words": [
        { "en": "biscuit", "pos": "n", "zh": "餅乾（英）" },
        { "en": "cookie", "pos": "n", "zh": "餅乾（美）" },
        { "en": "butter", "pos": "n", "zh": "奶油" },
        { "en": "cereal", "pos": "n", "zh": "穀片；麥片" },
        { "en": "flour", "pos": "n", "zh": "麵粉" },
        { "en": "honey", "pos": "n", "zh": "蜂蜜" },
        { "en": "jam", "pos": "n", "zh": "果醬" },
        { "en": "meal", "pos": "n", "zh": "一餐" },
        { "en": "olives", "pos": "n", "zh": "橄欖" },
        { "en": "pepper", "pos": "n", "zh": "胡椒；甜椒" },
        { "en": "pizza", "pos": "n", "zh": "披薩" },
        { "en": "snack", "pos": "n", "zh": "點心；小吃" },
        { "en": "strawberry", "pos": "n", "zh": "草莓" },
        { "en": "sugar", "pos": "n", "zh": "糖" },
        { "en": "yoghurt", "pos": "n", "zh": "優格；優酪乳" }
      ]
    },
    {
      "id": "home_buildings",
      "label": "家裡・建築物",
      "icon": "🏠",
      "words": [
        { "en": "bank", "pos": "n", "zh": "銀行" },
        { "en": "castle", "pos": "n", "zh": "城堡" },
        { "en": "cave", "pos": "n", "zh": "洞穴" },
        { "en": "chemist(’s)", "pos": "n", "zh": "藥局；藥房" },
        { "en": "college", "pos": "n", "zh": "學院；大專院校" },
        { "en": "cooker", "pos": "n", "zh": "瓦斯爐；電鍋等爐具" },
        { "en": "entrance", "pos": "n", "zh": "入口" },
        { "en": "environment", "pos": "n", "zh": "環境" },
        { "en": "factory", "pos": "n", "zh": "工廠" },
        { "en": "fire station", "pos": "n", "zh": "消防局" },
        { "en": "hotel", "pos": "n", "zh": "飯店；旅館" },
        { "en": "museum", "pos": "n", "zh": "博物館" },
        { "en": "office", "pos": "n", "zh": "辦公室" },
        { "en": "police station", "pos": "n", "zh": "警察局" },
        { "en": "post office", "pos": "n", "zh": "郵局" },
        { "en": "restaurant", "pos": "n", "zh": "餐廳" },
        { "en": "stadium", "pos": "n", "zh": "體育場" },
        { "en": "stage", "pos": "n", "zh": "舞台" },
        { "en": "stream", "pos": "n", "zh": "小溪（也可算自然）" }
      ]
    },
    {
      "id": "places_town",
      "label": "城市裡的地方",
      "icon": "🏙️",
      "words": [
        { "en": "airport", "pos": "n", "zh": "機場" },
        { "en": "bank", "pos": "n", "zh": "銀行" },
        { "en": "castle", "pos": "n", "zh": "城堡" },
        { "en": "chemist(’s)", "pos": "n", "zh": "藥局" },
        { "en": "college", "pos": "n", "zh": "學院" },
        { "en": "factory", "pos": "n", "zh": "工廠" },
        { "en": "fire station", "pos": "n", "zh": "消防局" },
        { "en": "gym", "pos": "n", "zh": "體育館；健身房" },
        { "en": "hotel", "pos": "n", "zh": "飯店；旅館" },
        { "en": "museum", "pos": "n", "zh": "博物館" },
        { "en": "office", "pos": "n", "zh": "辦公室" },
        { "en": "police station", "pos": "n", "zh": "警察局" },
        { "en": "post office", "pos": "n", "zh": "郵局" },
        { "en": "restaurant", "pos": "n", "zh": "餐廳" },
        { "en": "stadium", "pos": "n", "zh": "體育場" },
        { "en": "station", "pos": "n", "zh": "車站（如有出現）" },
        { "en": "theatre", "pos": "n", "zh": "劇院" }
      ]
    },
    {
      "id": "nature_world_weather",
      "label": "自然・世界・天氣",
      "icon": "⛰️",
      "words": [
        { "en": "air", "pos": "n", "zh": "空氣" },
        { "en": "autumn", "pos": "n", "zh": "秋天（英）" },
        { "en": "fall", "pos": "n", "zh": "秋天（美）" },
        { "en": "desert", "pos": "n", "zh": "沙漠" },
        { "en": "Earth", "pos": "n", "zh": "地球" },
        { "en": "east", "pos": "n", "zh": "東方；東邊" },
        { "en": "environment", "pos": "n", "zh": "環境" },
        { "en": "fog", "pos": "n", "zh": "霧" },
        { "en": "foggy", "pos": "adj", "zh": "有霧的" },
        { "en": "future", "pos": "n", "zh": "未來" },
        { "en": "hill", "pos": "n", "zh": "小山；丘陵" },
        { "en": "north", "pos": "n", "zh": "北方" },
        { "en": "south", "pos": "n", "zh": "南方" },
        { "en": "west", "pos": "n", "zh": "西方" },
        { "en": "ocean", "pos": "n", "zh": "大海；海洋" },
        { "en": "space", "pos": "n", "zh": "太空；空間" },
        { "en": "storm", "pos": "n", "zh": "暴風雨" },
        { "en": "summer", "pos": "n", "zh": "夏天" },
        { "en": "winter", "pos": "n", "zh": "冬天" }
      ]
    },
    {
      "id": "media_tech_school",
      "label": "媒體・科技・學習",
      "icon": "💻",
      "words": [
        { "en": "act", "pos": "v", "zh": "表演；演戲" },
        { "en": "art", "pos": "n", "zh": "藝術" },
        { "en": "band", "pos": "n", "zh": "樂團" },
        { "en": "cartoon", "pos": "n", "zh": "卡通；漫畫" },
        { "en": "channel", "pos": "n", "zh": "頻道" },
        { "en": "chat", "pos": "v", "zh": "聊天" },
        { "en": "college", "pos": "n", "zh": "學院；大學" },
        { "en": "competition", "pos": "n", "zh": "比賽；競賽" },
        { "en": "concert", "pos": "n", "zh": "音樂會" },
        { "en": "conversation", "pos": "n", "zh": "對話" },
        { "en": "diary", "pos": "n", "zh": "日記" },
        { "en": "dictionary", "pos": "n", "zh": "字典" },
        { "en": "file", "pos": "n", "zh": "檔案" },
        { "en": "festival", "pos": "n", "zh": "節慶；慶典" },
        { "en": "geography", "pos": "n", "zh": "地理（課）" },
        { "en": "history", "pos": "n", "zh": "歷史（課）" },
        { "en": "information", "pos": "n", "zh": "資訊；資料" },
        { "en": "instrument", "pos": "n", "zh": "樂器" },
        { "en": "magazine", "pos": "n", "zh": "雜誌" },
        { "en": "maths", "pos": "n", "zh": "數學（英）" },
        { "en": "news", "pos": "n", "zh": "新聞" },
        { "en": "newspaper", "pos": "n", "zh": "報紙" },
        { "en": "online", "pos": "adj", "zh": "線上的" },
        { "en": "pop music", "pos": "n", "zh": "流行音樂" },
        { "en": "programme", "pos": "n", "zh": "節目；程式（英）" },
        { "en": "project", "pos": "n", "zh": "專題；計畫" },
        { "en": "science", "pos": "n", "zh": "自然科學" },
        { "en": "screen", "pos": "n", "zh": "螢幕" },
        { "en": "subject", "pos": "n", "zh": "科目；主題" },
        { "en": "timetable", "pos": "n", "zh": "時間表；課表" },
        { "en": "wifi", "pos": "n", "zh": "無線網路" }
      ]
    },
    {
      "id": "free_time_sports",
      "label": "休閒・運動・遊樂",
      "icon": "⚽",
      "words": [
        { "en": "adventure", "pos": "n", "zh": "冒險" },
        { "en": "camp", "pos": "v", "zh": "露營" },
        { "en": "club", "pos": "n", "zh": "社團；俱樂部" },
        { "en": "competition", "pos": "n", "zh": "比賽" },
        { "en": "concert", "pos": "n", "zh": "音樂會" },
        { "en": "festival", "pos": "n", "zh": "節慶" },
        { "en": "gym", "pos": "n", "zh": "體育館；健身房" },
        { "en": "pop music", "pos": "n", "zh": "流行音樂" },
        { "en": "race", "pos": "n/v", "zh": "賽跑；比賽；競賽" },
        { "en": "racing", "pos": "adj", "zh": "競賽用的（車／腳踏車）" },
        { "en": "rock music", "pos": "n", "zh": "搖滾音樂" },
        { "en": "ski", "pos": "n/v", "zh": "滑雪；滑雪板" },
        { "en": "snowball", "pos": "n", "zh": "雪球" },
        { "en": "snowboard", "pos": "n", "zh": "滑雪板" },
        { "en": "snowboarding", "pos": "n", "zh": "滑雪運動" },
        { "en": "snowman", "pos": "n", "zh": "雪人" },
        { "en": "swing", "pos": "n/v", "zh": "鞦韆；盪鞦韆" },
        { "en": "tour", "pos": "n", "zh": "旅遊團；旅行" },
        { "en": "violin", "pos": "n", "zh": "小提琴" },
        { "en": "volleyball", "pos": "n", "zh": "排球" }
      ]
    },
    {
      "id": "transport_travel",
      "label": "交通・旅行",
      "icon": "🚗",
      "words": [
        { "en": "a.m.", "pos": "adv", "zh": "上午；…點 a.m." },
        { "en": "p.m.", "pos": "adv", "zh": "下午；…點 p.m." },
        { "en": "airport", "pos": "n", "zh": "機場" },
        { "en": "backpack", "pos": "n", "zh": "背包（美）" },
        { "en": "rucksack", "pos": "n", "zh": "背包（英）" },
        { "en": "journey", "pos": "n", "zh": "旅程" },
        { "en": "motorway", "pos": "n", "zh": "高速公路（英）" },
        { "en": "passenger", "pos": "n", "zh": "乘客" },
        { "en": "platform", "pos": "n", "zh": "月台" },
        { "en": "taxi", "pos": "n", "zh": "計程車" },
        { "en": "tour", "pos": "n", "zh": "旅行；觀光團" },
        { "en": "traffic", "pos": "n", "zh": "交通" },
        { "en": "trainers", "pos": "n", "zh": "運動鞋（英）" },
        { "en": "tyre", "pos": "n", "zh": "輪胎（英）" },
        { "en": "umbrella", "pos": "n", "zh": "雨傘" },
        { "en": "wheel", "pos": "n", "zh": "輪子" }
      ]
    },
    {
      "id": "time_days_numbers",
      "label": "時間・星期・數字",
      "icon": "⏰",
      "words": [
        { "en": "April", "pos": "n", "zh": "四月" },
        { "en": "August", "pos": "n", "zh": "八月" },
        { "en": "autumn", "pos": "n", "zh": "秋天" },
        { "en": "December", "pos": "n", "zh": "十二月" },
        { "en": "February", "pos": "n", "zh": "二月" },
        { "en": "January", "pos": "n", "zh": "一月" },
        { "en": "July", "pos": "n", "zh": "七月" },
        { "en": "June", "pos": "n", "zh": "六月" },
        { "en": "March", "pos": "n", "zh": "三月" },
        { "en": "May", "pos": "n", "zh": "五月" },
        { "en": "November", "pos": "n", "zh": "十一月" },
        { "en": "October", "pos": "n", "zh": "十月" },
        { "en": "midday", "pos": "n", "zh": "中午" },
        { "en": "midnight", "pos": "n", "zh": "午夜；半夜十二點" },
        { "en": "minute", "pos": "n", "zh": "分鐘" },
        { "en": "hour", "pos": "n", "zh": "小時" },
        { "en": "time", "pos": "n", "zh": "時間" },
        { "en": "timetable", "pos": "n", "zh": "時間表" },
        { "en": "tomorrow", "pos": "adv/n", "zh": "明天" },
        { "en": "tonight", "pos": "adv/n", "zh": "今晚" },
        { "en": "quarter", "pos": "n", "zh": "四分之一；一刻鐘" },
        { "en": "thousand", "pos": "n", "zh": "一千" },
        { "en": "million", "pos": "n", "zh": "一百萬" },
        { "en": "zero", "pos": "n", "zh": "零" },
        { "en": "a few", "pos": "det", "zh": "幾個；一些" },
        { "en": "much", "pos": "adv/det/pron", "zh": "很多；多（不可數）" },
        { "en": "yet", "pos": "adv", "zh": "還；尚未" }
      ]
    },
    {
      "id": "objects_clothes_things",
      "label": "物品・衣服・東西",
      "icon": "🧺",
      "words": [
        { "en": "backpack", "pos": "n", "zh": "背包" },
        { "en": "belt", "pos": "n", "zh": "皮帶" },
        { "en": "bin", "pos": "n", "zh": "垃圾桶" },
        { "en": "bracelet", "pos": "n", "zh": "手鍊" },
        { "en": "brush", "pos": "n", "zh": "刷子" },
        { "en": "business card", "pos": "n", "zh": "名片（如出現）" },
        { "en": "calendar", "pos": "n", "zh": "月曆；行事曆" },
        { "en": "card", "pos": "n", "zh": "卡片；卡" },
        { "en": "comb", "pos": "n", "zh": "梳子" },
        { "en": "crown", "pos": "n", "zh": "王冠；皇冠" },
        { "en": "costume", "pos": "n", "zh": "戲服；服裝" },
        { "en": "cushion", "pos": "n", "zh": "靠墊；坐墊" },
        { "en": "diary", "pos": "n", "zh": "日記" },
        { "en": "envelope", "pos": "n", "zh": "信封" },
        { "en": "file", "pos": "n", "zh": "檔案" },
        { "en": "flag", "pos": "n", "zh": "旗子" },
        { "en": "flashlight", "pos": "n", "zh": "手電筒（美）" },
        { "en": "torch", "pos": "n", "zh": "手電筒（英）" },
        { "en": "fork", "pos": "n", "zh": "叉子" },
        { "en": "fridge", "pos": "n", "zh": "冰箱" },
        { "en": "glass", "pos": "adj", "zh": "玻璃的" },
        { "en": "glove", "pos": "n", "zh": "手套" },
        { "en": "glue", "pos": "n/v", "zh": "膠水；黏貼" },
        { "en": "gold", "pos": "adj/n", "zh": "金色的；黃金" },
        { "en": "jam", "pos": "n", "zh": "果醬" },
        { "en": "key", "pos": "n", "zh": "鑰匙" },
        { "en": "knife", "pos": "n", "zh": "刀" },
        { "en": "letter", "pos": "n", "zh": "信件" },
        { "en": "lift", "pos": "n", "zh": "搭便車；一程" },
        { "en": "light", "pos": "adj/n", "zh": "輕的；光；燈" },
        { "en": "necklace", "pos": "n", "zh": "項鍊" },
        { "en": "nest", "pos": "n", "zh": "巢；鳥巢" },
        { "en": "pajamas", "pos": "n", "zh": "睡衣（美）" },
        { "en": "pyjamas", "pos": "n", "zh": "睡衣（英）" },
        { "en": "pocket", "pos": "n", "zh": "口袋" },
        { "en": "postcard", "pos": "n", "zh": "明信片" },
        { "en": "ring", "pos": "n", "zh": "戒指" },
        { "en": "rucksack", "pos": "n", "zh": "背包" },
        { "en": "salt", "pos": "n", "zh": "鹽" },
        { "en": "scissors", "pos": "n", "zh": "剪刀" },
        { "en": "shampoo", "pos": "n", "zh": "洗髮精" },
        { "en": "shelf", "pos": "n", "zh": "架子；層板" },
        { "en": "soap", "pos": "n", "zh": "肥皂" },
        { "en": "spoon", "pos": "n", "zh": "湯匙" },
        { "en": "stamp", "pos": "n", "zh": "郵票" },
        { "en": "stone", "pos": "n", "zh": "石頭" },
        { "en": "strawberry", "pos": "n", "zh": "草莓" },
        { "en": "suitcase", "pos": "n", "zh": "行李箱" },
        { "en": "sunglasses", "pos": "n", "zh": "太陽眼鏡" },
        { "en": "tent", "pos": "n", "zh": "帳篷" },
        { "en": "toe", "pos": "n", "zh": "腳趾" },
        { "en": "trainers", "pos": "n", "zh": "運動鞋" },
        { "en": "tyre", "pos": "n", "zh": "輪胎" },
        { "en": "umbrella", "pos": "n", "zh": "雨傘" },
        { "en": "uniform", "pos": "n", "zh": "制服" },
        { "en": "view", "pos": "n", "zh": "景色；視野" },
        { "en": "wheel", "pos": "n", "zh": "輪子" },
        { "en": "wood", "pos": "n", "zh": "木頭" },
        { "en": "wool", "pos": "n", "zh": "羊毛" }
      ]
    },
    {
      "id": "actions",
      "label": "一般動作動詞",
      "icon": "🏃",
      "words": [
        { "en": "act", "pos": "v", "zh": "表演；演戲" },
        { "en": "agree", "pos": "v", "zh": "同意" },
        { "en": "appear", "pos": "v", "zh": "出現" },
        { "en": "arrive", "pos": "v", "zh": "到達" },
        { "en": "begin", "pos": "v", "zh": "開始" },
        { "en": "believe", "pos": "v", "zh": "相信" },
        { "en": "borrow", "pos": "v", "zh": "借入" },
        { "en": "break", "pos": "v", "zh": "打破；弄壞" },
        { "en": "brush", "pos": "v", "zh": "刷；刷牙；梳頭" },
        { "en": "burn", "pos": "v", "zh": "燃燒；燒傷" },
        { "en": "camp", "pos": "v", "zh": "露營" },
        { "en": "chat", "pos": "v", "zh": "聊天" },
        { "en": "collect", "pos": "v", "zh": "收集" },
        { "en": "comb", "pos": "v", "zh": "梳頭髮" },
        { "en": "cook", "pos": "v", "zh": "煮飯；烹調" },
        { "en": "could", "pos": "v", "zh": "可以；能（可能性）" },
        { "en": "cut", "pos": "v", "zh": "切；割" },
        { "en": "cycle", "pos": "v", "zh": "騎腳踏車" },
        { "en": "decide", "pos": "v", "zh": "決定" },
        { "en": "disappear", "pos": "v", "zh": "消失" },
        { "en": "design", "pos": "v", "zh": "設計" },
        { "en": "enter", "pos": "v", "zh": "參加（比賽）；進入" },
        { "en": "explore", "pos": "v", "zh": "探索" },
        { "en": "explain", "pos": "v", "zh": "解釋" },
        { "en": "fall over", "pos": "v", "zh": "跌倒" },
        { "en": "fetch", "pos": "v", "zh": "去拿；去取回" },
        { "en": "find out", "pos": "v", "zh": "查出；發現" },
        { "en": "finish", "pos": "v", "zh": "完成；結束" },
        { "en": "forget", "pos": "v", "zh": "忘記" },
        { "en": "follow", "pos": "v", "zh": "跟隨" },
        { "en": "get to", "pos": "v", "zh": "抵達；到達" },
        { "en": "go out", "pos": "v", "zh": "外出" },
        { "en": "guess", "pos": "v", "zh": "猜；猜測" },
        { "en": "happen", "pos": "v", "zh": "發生" },
        { "en": "hate", "pos": "v", "zh": "討厭" },
        { "en": "hear", "pos": "v", "zh": "聽見" },
        { "en": "hope", "pos": "v", "zh": "希望" },
        { "en": "hurry", "pos": "v", "zh": "趕快；趕緊" },
        { "en": "improve", "pos": "v", "zh": "改善；進步" },
        { "en": "invent", "pos": "v", "zh": "發明" },
        { "en": "keep", "pos": "v", "zh": "保持；保留" },
        { "en": "land", "pos": "v", "zh": "降落（飛機等）" },
        { "en": "leave", "pos": "v", "zh": "離開；留下" },
        { "en": "let", "pos": "v", "zh": "讓；允許" },
        { "en": "lie", "pos": "v", "zh": "躺下；躺著" },
        { "en": "look after", "pos": "v", "zh": "照顧" },
        { "en": "look like", "pos": "v", "zh": "看起來像" },
        { "en": "make sure", "pos": "v", "zh": "確定；確認" },
        { "en": "meet", "pos": "v", "zh": "見面；遇見" },
        { "en": "mind", "pos": "v", "zh": "介意" },
        { "en": "mix", "pos": "v", "zh": "混合；攪拌" },
        { "en": "post", "pos": "v", "zh": "寄信；貼上（網路）" },
        { "en": "prefer", "pos": "v", "zh": "比較喜歡" },
        { "en": "prepare", "pos": "v", "zh": "準備" },
        { "en": "pull", "pos": "v", "zh": "拉" },
        { "en": "push", "pos": "v", "zh": "推" },
        { "en": "race", "pos": "v", "zh": "賽跑；比賽" },
        { "en": "remember", "pos": "v", "zh": "記得" },
        { "en": "repair", "pos": "v", "zh": "修理" },
        { "en": "repeat", "pos": "v", "zh": "重複" },
        { "en": "save", "pos": "v", "zh": "拯救；存（檔、錢）" },
        { "en": "search", "pos": "v", "zh": "搜尋；尋找" },
        { "en": "sell", "pos": "v", "zh": "賣" },
        { "en": "ski", "pos": "v", "zh": "滑雪" },
        { "en": "smell", "pos": "v", "zh": "聞；聞起來" },
        { "en": "speak", "pos": "v", "zh": "說話" },
        { "en": "spend", "pos": "v", "zh": "花費（時間、金錢）" },
        { "en": "stay", "pos": "v", "zh": "停留；待在" },
        { "en": "study", "pos": "v", "zh": "讀書；學習" },
        { "en": "take", "pos": "v", "zh": "花（時間）；拿；搭乘" },
        { "en": "taste", "pos": "v", "zh": "嚐起來；品嚐" },
        { "en": "thank", "pos": "v", "zh": "感謝" },
        { "en": "tidy", "pos": "v", "zh": "整理" },
        { "en": "touch", "pos": "v", "zh": "觸碰" },
        { "en": "turn", "pos": "v", "zh": "轉動；轉向" },
        { "en": "turn off", "pos": "v", "zh": "關掉" },
        { "en": "turn on", "pos": "v", "zh": "打開（電源）" },
        { "en": "use", "pos": "v", "zh": "使用" },
        { "en": "visit", "pos": "v", "zh": "拜訪；參觀" },
        { "en": "wait", "pos": "v", "zh": "等待" },
        { "en": "whisper", "pos": "v", "zh": "悄悄說；低聲說" },
        { "en": "whistle", "pos": "v", "zh": "吹口哨" },
        { "en": "win", "pos": "v", "zh": "贏" },
        { "en": "wish", "pos": "v", "zh": "希望；祝願" }
      ]
    },
    {
      "id": "grammar_function",
      "label": "文法小字・介系詞・問句字",
      "icon": "📌",
      "words": [
        { "en": "across", "pos": "prep", "zh": "穿過；橫過" },
        { "en": "after", "pos": "adv/conj", "zh": "之後；在…之後" },
        { "en": "ago", "pos": "adv", "zh": "…之前" },
        { "en": "also", "pos": "adv", "zh": "也；還" },
        { "en": "already", "pos": "adv", "zh": "已經" },
        { "en": "anywhere", "pos": "adv", "zh": "任何地方" },
        { "en": "as", "pos": "adv", "zh": "像…一樣；如同" },
        { "en": "as ... as", "pos": "adv", "zh": "和…一樣…" },
        { "en": "at the moment", "pos": "adv", "zh": "此刻；現在" },
        { "en": "away", "pos": "adv", "zh": "離開；遠離" },
        { "en": "before", "pos": "adv/conj", "zh": "以前；在…之前" },
        { "en": "by myself", "pos": "adv", "zh": "自己一個人" },
        { "en": "by yourself", "pos": "adv", "zh": "你自己" },
        { "en": "each", "pos": "det/pron", "zh": "每一個" },
        { "en": "else", "pos": "adv", "zh": "別的；其他" },
        { "en": "enough", "pos": "adj/pron", "zh": "足夠的；足夠" },
        { "en": "ever", "pos": "adv", "zh": "曾經；任何時候" },
        { "en": "everywhere", "pos": "adv", "zh": "到處" },
        { "en": "far", "pos": "adj/adv", "zh": "遠的；很遠地" },
        { "en": "for", "pos": "prep", "zh": "持續…時間；給；為了" },
        { "en": "in", "pos": "prep", "zh": "在…裡；在…時" },
        { "en": "instead", "pos": "adv", "zh": "代替；而不是" },
        { "en": "much", "pos": "adv/det/pron", "zh": "很多；多" },
        { "en": "next", "pos": "adj/adv", "zh": "下一個；接著" },
        { "en": "nowhere", "pos": "adv", "zh": "哪裡也沒有" },
        { "en": "of course", "pos": "adv", "zh": "當然" },
        { "en": "once", "pos": "adv", "zh": "一次；曾經" },
        { "en": "over", "pos": "adv/prep", "zh": "在…之上；越過；結束" },
        { "en": "past", "pos": "n/prep", "zh": "過去；經過…" },
        { "en": "perhaps", "pos": "adv", "zh": "也許" },
        { "en": "quite", "pos": "adv", "zh": "相當；很" },
        { "en": "several", "pos": "adj", "zh": "好幾個" },
        { "en": "since", "pos": "prep", "zh": "自從…" },
        { "en": "so", "pos": "adv/conj", "zh": "所以；這麼" },
        { "en": "somewhere", "pos": "adv", "zh": "某處" },
        { "en": "still", "pos": "adv", "zh": "仍然；還" },
        { "en": "straight on", "pos": "adv", "zh": "直直往前" },
        { "en": "such", "pos": "det", "zh": "這樣的；那樣的" },
        { "en": "through", "pos": "prep", "zh": "穿過；經過" },
        { "en": "together", "pos": "adv", "zh": "一起" },
        { "en": "twice", "pos": "adv", "zh": "兩次" },
        { "en": "until", "pos": "prep", "zh": "直到…" },
        { "en": "usually", "pos": "adv", "zh": "通常" },
        { "en": "while", "pos": "conj", "zh": "當…的時候" },
        { "en": "without", "pos": "prep", "zh": "沒有…；不帶…" },

        { "en": "how long", "pos": "adv/int", "zh": "多久" },

        { "en": "if", "pos": "conj", "zh": "如果" },
        { "en": "may", "pos": "v", "zh": "可能；也許" },
        { "en": "might", "pos": "v", "zh": "可能；也許" },
        { "en": "should", "pos": "v", "zh": "應該" },
        { "en": "will", "pos": "v", "zh": "將要；會" },

        { "en": "actually", "pos": "adv", "zh": "其實；實際上" },
        { "en": "just", "pos": "adv", "zh": "剛剛；只是" },
        { "en": "no problem!", "pos": "excl", "zh": "沒問題！" },
        { "en": "go away!", "pos": "excl", "zh": "走開！" },
        { "en": "if you want!", "pos": "excl", "zh": "如果你想要的話！" },
        { "en": "in a minute!", "pos": "excl", "zh": "再一下下！" },
        { "en": "you’re welcome!", "pos": "excl", "zh": "不客氣！" }
      ]
    }
  ]
};

// 統一封裝給主程式用
const DATASETS = {
  starters: STARTERS_DATA,
  movers:   MOVERS_DATA,
  flyers:   FLYERS_DATA
};
